name: "Hugo on Fire"
description: "A Github action build a Hugo site and then deploy it to Firebase Hosting"
author: "Wajahat Karim (https://wajahatkarim.com)"

branding:
  icon: 'arrow-up-right'
  color: 'red'
  label: 'Hugo On Fire'

inputs:
  gcp_sa_key:
    description: "Service account key in json. Set it in Github Secrets as FIREBASE_SERVICE_ACCOUNT variable."
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.gcp_sa_key }}
